# rest server config
server:
  port: 8080

spring:
  jpa:
    hibernate.ddl-auto: validate
  # h2 test database config
  datasource.url: jdbc:h2:mem:testdb
  datasource.driverClassName: org.h2.Driver
  datasource.username: sa
  datasource.password:
  h2.console.enabled: true

# liquibase config
liquibase.change-log: classpath:db/match-changelog-catalog.xml
